version: "3.9"

services:
  api:
    build: .
    container_name: node-api
    env_file: .env
    ports:
      - "3000:3000"
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: redis
    command: >
      redis-server
      --appendonly yes
      --save 60 1000
      --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"  # expose only to host, not LAN
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 3s
      timeout: 2s
      retries: 20
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
